### ISSUE TITLE
ClasspathScanner does not integrate with lambda expressions

### ISSUE THREAD

**Issue by timkral** [Netflix/governator#188]
I'm using governator's classpath scan functionality to find auto bind classes. Here's a snippet:
```java
final LifecycleInjector lifecycleInjector;
try {
    lifecycleInjector = LifecycleInjector.builder()
        .usingBasePackages("my.base.package")
        .build();
} catch (Throwable t) {
    LOGGER.error("Error during LifecycleInjector build", t);
    throw t;
}
```
If I include a lambda expression in any of the classes that get scanned, I get the following exception:
```java
ERROR [2015-04-03 07:17:07,112] my.base.package.app.MyApplication: Error during LifecycleInjector build
! java.lang.ArrayIndexOutOfBoundsException: 52264
! at org.objectweb.asm.ClassReader.readClass(Unknown Source) ~[asm-all-3.2.jar:3.2]
! at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-3.2.jar:3.2]
! at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-3.2.jar:3.2]
! at org.apache.xbean.finder.AnnotationFinder.readClassDef(AnnotationFinder.java:958) ~[xbean-finder-3.11.1.jar:3.11.1]
! at org.apache.xbean.finder.AnnotationFinder.<init>(AnnotationFinder.java:120) ~[xbean-finder-3.11.1.jar:3.11.1]
! at com.netflix.governator.lifecycle.ClasspathScanner.doScanning(ClasspathScanner.java:141) ~[governator-1.3.3.jar:na]
! at com.netflix.governator.lifecycle.ClasspathScanner.<init>(ClasspathScanner.java:82) ~[governator-1.3.3.jar:na]
! at com.netflix.governator.lifecycle.ClasspathScanner.<init>(ClasspathScanner.java:61) ~[governator-1.3.3.jar:na]
! at com.netflix.governator.guice.LifecycleInjector.createStandardClasspathScanner(LifecycleInjector.java:286) ~[governator-1.3.3.jar:na]
! at com.netflix.governator.guice.LifecycleInjector.createStandardClasspathScanner(LifecycleInjector.java:263) ~[governator-1.3.3.jar:na]
! at com.netflix.governator.guice.LifecycleInjector.<init>(LifecycleInjector.java:399) ~[governator-1.3.3.jar:na]
! at com.netflix.governator.guice.LifecycleInjectorBuilderImpl.build(LifecycleInjectorBuilderImpl.java:309) ~[governator-1.3.3.jar:na]
! ... 7 common frames omitted
! Causing: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 52264
! at com.netflix.governator.guice.LifecycleInjectorBuilderImpl.build(LifecycleInjectorBuilderImpl.java:311) ~[governator-1.3.3.jar:na]
! at my.base.package.app.MyApplication.run(MyApplication.java:43) [classes/:na]
! at my.base.package.app.MyApplication.run(MyApplication.java:19) [classes/:na]
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42) [dropwizard-core-0.8.0.jar:0.8.0]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76) [dropwizard-core-0.8.0.jar:0.8.0]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [dropwizard-core-0.8.0.jar:0.8.0]
! at io.dropwizard.Application.run(Application.java:73) [dropwizard-core-0.8.0.jar:0.8.0]
! at my.base.package.app.MyApplication.main(MyApplication.java:26) [classes/:na]
```
 After a little research, I discovered that the asm and xbean dependencies that ship with governator are old and do not support Java 8: http://stackoverflow.com/questions/26496338/strange-java-lang-arrayindexoutofboundsexception-thrown-on-jetty-startup

I was able to work around this issue by excluding these dependencies and adding newer versions with a runtime scope:
```xml
<dependency>
    <groupId>com.netflix.governator</groupId>
    <artifactId>governator</artifactId>
    <version>1.3.3</version>
    <exclusions>
        <exclusion>
            <groupId>asm</groupId>
            <artifactId>asm-all</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.apache.xbean</groupId>
            <artifactId>xbean-bundleutils</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.apache.xbean</groupId>
            <artifactId>xbean-finder</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>org.apache.xbean</groupId>
    <artifactId>xbean-bundleutils</artifactId>
    <version>3.17</version>
    <scope>runtime</scope>
</dependency>
<dependency>
    <groupId>org.apache.xbean</groupId>
    <artifactId>xbean-finder</artifactId>
    <version>3.17</version>
    <scope>runtime</scope>
</dependency>
<dependency>
    <groupId>org.ow2.asm</groupId>
    <artifactId>asm-all</artifactId>
    <version>5.0.1</version>
    <scope>runtime</scope>
</dependency>
```
Luckily, this combination seems to be just enough to get me past this issue without causing other runtime problems. However, it would be nice if governator updated its dependencies so Java 8 features are supported without these gymnastics.

**Comment by timkral** [comment]
Governator has deprecated auto binding through classpath scanning.
